-- CREATE TABLE DEPT1(
-- EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
-- NAME VARCHAR(255) NOT NULL,
-- ROLE VARCHAR(25) NOT NULL
-- );

-- INSERT INTO DEPT1(NAME,ROLE) VALUES
-- ("SOURAV","ENGINEER"),
-- ("ROHIT","SALES MAN"),
-- ("RAGHU","MANAGER"),
-- ("VIKRAM","SALES MAN"),
-- ("ARJUN","ENGINEER");

-- CREATE TABLE DEPT2(
-- EMP_ID INT PRIMARY KEY,
-- NAME VARCHAR(255) NOT NULL,
-- ROLE VARCHAR(25) NOT NULL
-- );

-- INSERT INTO DEPT2(EMP_ID,NAME,ROLE) VALUES
-- (3,"RAGHU","MANAGER"),
-- (6,"JOYDEEP","MARKETING"),
-- (7,"LULEN","SALESMAN");

SELECT * FROM DEPT1;
SELECT * FROM DEPT2;

-- LIST OUT ALL THE EMPLOYEE IN THIS COMPANY
SELECT * FROM DEPT1 
UNION
SELECT * FROM DEPT2;

-- LIST OUT ALL THE EMPLOYEE IN ALL DEPARTMENTS WHO WORKS AS SALES MAN (UNION)
SELECT * FROM DEPT1 WHERE ROLE = "SALES MAN"
UNION
SELECT * FROM DEPT2 WHERE ROLE = "SALES MAN";

-- LIST OUT ALL THE EMPLOYEES WHO WORK FOR BOTH THE DEPARTMENTS (INTERSECTION)
SELECT D1.EMP_ID,D1.NAME,D1.ROLE FROM DEPT1 AS D1
INNER JOIN DEPT2 AS D2 USING(EMP_ID)
WHERE D1.EMP_ID = D2.EMP_ID;

-- LIST OUT ALL THE EMPLOYEES WORKING IN DEPARTMENT 1 BUT NOT IN DEPARTMENT 2 (DIFFERENCE)
SELECT D1.* FROM DEPT1 AS D1
LEFT JOIN
DEPT2 AS D2 USING(EMP_ID)
WHERE D2.EMP_ID IS NULL;