SELECT * FROM EMPLOYEE; -- SHOWS THE ORIGINAL TABLE WHICH IS CREATED IN ACTUAL MEMORY

-- CREATING A VIEW

CREATE VIEW CUSTOM_VIEW AS SELECT FNAME,AGE FROM EMPLOYEE;

-- VIEWING FROM VIEW 
SELECT * FROM CUSTOM_VIEW;

-- ALTERING VIEW 

ALTER VIEW CUSTOM_VIEW AS 
SELECT FNAME,LNAME,AGE
FROM EMPLOYEE;

SELECT * FROM CUSTOM_VIEW;

-- DROPING THE VIEW
DROP VIEW IF EXISTS CUSTOM_VIEW;