SELECT * FROM TEMP.EMPLOYEE;
SELECT * FROM TEMP.PROJECT;
SELECT * FROM TEMP.CLIENT;

-- WHERE CLAUSE SAME TABLE
-- EMPLOYEE WITH AGE > 30
SELECT * FROM EMPLOYEE WHERE AGE IN 
(
SELECT AGE FROM EMPLOYEE WHERE AGE>30
);

-- WHERE CLAUSE DIFFERENT TABLE
-- EMP DETAILS WORKING IN MORE THAN 1 PROJECTS
SELECT * FROM EMPLOYEE WHERE ID IN
(
SELECT EMPID FROM PROJECT GROUP BY EMPID HAVING COUNT(EMPID) > 1
);

-- SINGLE VALUE SUBQUERY
-- EMPLOYEE DETAIL HAVING AGE > AVERAGE AGE

SELECT * FROM EMPLOYEE 
WHERE AGE > 
(
SELECT AVG(AGE) FROM EMPLOYEE
);

-- SUB QUERY WITH FROM CLAUSE
-- SELECT MAX AGE EMPLOYEE WHOSE FIRST NAME CONTAINS 'A'

SELECT MAX(AGE) FROM (SELECT * FROM EMPLOYEE WHERE FNAME LIKE "%A%") AS TEMP;


-- CORELATED SUB QUERIES
-- FIND THIRD OLDEST EMPLOYEE

SELECT *
FROM EMPLOYEE AS E1
WHERE 3 = (
SELECT COUNT(E2.AGE)
FROM EMPLOYEE AS E2
WHERE E2.AGE >= E1.AGE
);