-- PRIMARY TABLE
-- CREATE TABLE EMPLOYEE 
-- (
-- ID INT PRIMARY KEY AUTO_INCREMENT,
-- FNAME VARCHAR(200) NOT NULL,
-- LNAME VARCHAR(200) NOT NULL,
-- AGE INT NOT NULL,
-- EMAILID VARCHAR(200) NOT NULL,
-- PHONENO BIGINT NOT NULL,
-- CITY VARCHAR(200) NOT NULL
-- );

-- INSERT INTO EMPLOYEE(FNAME,LNAME,AGE,EMAILID,PHONENO,CITY) 
-- VALUES
-- ("AMAN","KUMAR",32,"aman324@yahoomail.com",7008812936,"DELHI"),
-- ("AMIT","NARAYAN",44,"amit567@example.com",7008812935,"CHANDIGARH"),
-- ("RAHUL","SHARMA",35,"rahul667@gmail.com",8093904565,"CUTTACK"),
-- ("RONIT","KUMAR",27,"ronit991@zohomail.com",7994568921,"BHUBANESWAR"),
-- ("SOUMYA","SAHU",29,"soumya234@microsoft.com",7894561230,"PARADIP");


-- PROJECT TABLE
-- CREATE TABLE PROJECT 
-- (
-- ID INT PRIMARY KEY AUTO_INCREMENT,
-- EMPID INT,
-- NAME VARCHAR(200) NOT NULL,
-- STARTDATE DATE NOT NULL,
-- CLIENTID INT,
-- FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(ID) ON DELETE SET NULL,
-- FOREIGN KEY(CLIENTID) REFERENCES CLIENT(ID) ON DELETE SET NULL
-- );
-- INSERT INTO PROJECT (EMPID,NAME,STARTDATE,CLIENTID) VALUES
-- (1,"AI BASED SEARCH ENGINE","2021-04-21",3),
-- (2,"RETAIL BUSINESS SOFTWARE","2021-03-12",1),
-- (3,"CLOUD BASED NOTE BOOK","2022-04-30",5),
-- (3,"AI BASED WEB CAM","2023-02-01",2),
-- (5,"BITCOIN BASED UPI","2021-12-21",4);
-- CLIENT TABLE
-- CREATE TABLE CLIENT 
-- (
-- ID INT PRIMARY KEY AUTO_INCREMENT,
-- FNAME VARCHAR(200) NOT NULL,
-- LNAME VARCHAR(200) NOT NULL,
-- AGE INT NOT NULL,
-- EMAILID VARCHAR(200) NOT NULL,
-- PHONENO BIGINT NOT NULL,
-- CITY VARCHAR(200) NOT NULL,
-- EMPID INT,
-- FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(ID) ON DELETE SET NULL
-- );
-- INSERT INTO CLIENT(FNAME,LNAME,AGE,EMAILID,PHONENO,CITY,EMPID) 
-- VALUES
-- ("ANUBHAB","KUMAR",32,"anubhab324@yahoomail.com",7008812936,"DELHI",3),
-- ("BHABESH","NARAYAN",44,"bhabesh567@example.com",7008812935,"CHANDIGARH",3),
-- ("TATHAGAT","SHARMA",35,"tathagat667@gmail.com",8093904565,"CUTTACK",1),
-- ("AMLAN","KUMAR",27,"amlan991@zohomail.com",7994568921,"BHUBANESWAR",5),
-- ("RAHUL","SAHU",29,"rahul234@microsoft.com",7894561230,"PARADIP",2);



SELECT * FROM temp.EMPLOYEE;
SELECT * FROM temp.PROJECT;
SELECT * FROM temp.CLIENT;





-- PRACTICE QUESTIONS ON JOIN
-- LIST ALL THE EMPLOYEES ID'S NAMES ALONG THE PROJECT ALLOCATED TO THEM
SELECT E.ID,E.FNAME,E.LNAME,P.ID,P.NAME 
FROM EMPLOYEE AS E
INNER JOIN 
PROJECT AS P
ON E.ID = P.EMPID;

-- FETCH OUT ALL THE EMPLOUEE ID'S AND THEIR CONTACT WHO HAVE BEEN WORKING FROM DELHI WITH THE CLIENT NAME WORKING IN CUTTACK
SELECT E.ID,E.FNAME,E.LNAME,E.EMAILID,E.CITY,C.ID,C.FNAME,C.LNAME,C.CITY 
FROM EMPLOYEE AS E
INNER JOIN
CLIENT AS C
ON E.ID = C.EMPID WHERE E.CITY = "DELHI" AND C.CITY = "CUTTACK";

-- LEFT JOIN
-- FETCH OUT EACH PROJECT ALLOCATED TO EACH EMPLOYEE
SELECT E.FNAME,E.LNAME,E.EMAILID,P.NAME
FROM EMPLOYEE E
LEFT JOIN
PROJECT P
ON E.ID = P.EMPID;

SELECT *,P.NAME
FROM EMPLOYEE E
LEFT JOIN
PROJECT P
ON E.ID = P.EMPID;


-- RIGHT JOIN
--  LIST OUT ALL THE PROJECTS ALONG WITH THE EMPLOYEE NAME AND THEIR RESPECTIVE EMAIL ID
SELECT P.ID,P.NAME,E.FNAME,E.LNAME,E.EMAILID FROM EMPLOYEE AS E
RIGHT JOIN
PROJECT P
ON E.ID = P.EMPID;


-- CROSS JOIN
-- LIST ALL THE COMBINATIONS POSSIBLE FOR THE EMPLOYEE NAME AND PROJECTS THAT CAN EXIST
SELECT E.FNAME,E.LNAME,P.ID,P.NAME 
FROM EMPLOYEE E
CROSS JOIN
PROJECT P;


-- WITHOUT JOIN KEY WORD
SELECT E.FNAME,E.LNAME,E.EMAILID,P.NAME
FROM EMPLOYEE E ,
PROJECT P
WHERE E.ID = P.EMPID;


-- SELF JOIN
SELECT P.ID,P.NAME,Q.EMPID FROM PROJECT AS P
INNER JOIN
PROJECT AS Q
ON P.ID = Q.EMPID;

-- FULL JOIN
SELECT E.FNAME, E.LNAME, E.EMAILID, P.NAME
FROM EMPLOYEE E
LEFT JOIN PROJECT P
  ON E.ID = P.EMPID

UNION

SELECT E.FNAME, E.LNAME, E.EMAILID, P.NAME
FROM EMPLOYEE E
RIGHT JOIN PROJECT P
  ON E.ID = P.EMPID;
